version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: appointment
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"